linters:
  disable-all: true
  enable:
    - asciicheck
    - contextcheck
    - copyloopvar
    - dogsled
    - errcheck
    - errorlint
    - gci
    - gocritic
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude:
    - 'Error return value of .[a-zA-Z0-9_.]+\.Write. is not checked'

service:
  golangci-lint-version: 1.62.x # use the fixed version to not introduce new linters unexpectedly
