linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - errorlint
    - exportloopref
    - gci
    - gocritic
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - golint
    - gomodguard
    - goprintffuncname
    - ifshort
    - ineffassign
    - interfacer
    - lll
    - makezero
    - maligned
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace

    # Don't enable:
    # - dupl
    # - exhaustive
    # - exhaustivestruct
    # - forbidigo
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    # - goconst
    # - gocyclo
    # - goerr113
    # - gofumpt
    # - gomnd
    # - nestif
    # - nlreturn
    # - paralleltest
    # - testpackage
    # - wrapcheck
    # - wsl

issues:
  exclude:
    - 'Error return value of .[a-zA-Z0-9_.]+\.Write. is not checked'

service:
  golangci-lint-version: 1.36.x # use the fixed version to not introduce new linters unexpectedly
