language: go
os:
  - linux
dist: xenial
go_import_path: github.com/diseaz/go-spew
go:
    - 1.17.x
    - tip
install:
    - go get -v github.com/golangci/golangci-lint@v1.62.2
script:
    - export PATH=$PATH:$HOME/gopath/bin
    - export GORACE="halt_on_error=1"
    - test -z "$(golangci-lint run ./spew | tee /dev/stderr)"
    - go test -v -race -tags safe ./spew
    - go test -v -race -tags testcgo ./spew -covermode=atomic -coverprofile=profile.cov
after_success:
    - go get -v github.com/mattn/goveralls
    - goveralls -coverprofile=profile.cov -service=travis-ci
